### ISSUE TITLE
DatePicker gifs

### ISSUE THREAD

**Issue by jmpressman** [mercurymedia/elm-datetime-picker#1]
![SinglePicker](https://user-images.githubusercontent.com/20546636/64876897-82b2e280-d650-11e9-8b36-5609125b1665.gif)
![DurationPicker](https://user-images.githubusercontent.com/20546636/64876920-91999500-d650-11e9-8f56-3088930b64f7.gif)

**Comment by Tranquility** [comment]
No need for this to be an open issue :)
