### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by rl-king** [mercurymedia/elm-datetime-picker#18]
When are you planning on releasing the next version of this package? I see #15 removes the need for the confirmation button and that's exactly what we need :)

Thanks!

**Comment by jmpressman** [comment]
Hi Ruben,

I would expect a release before the end of January as there are still a few more issues we are hoping to resolve with the next release. I realize that may be a bit later than you are hoping, but I am currently out of office until the end of this week, and the other team members have their hands full at the moment.

I guarantee the wait will be worth it.

John

**Comment by rl-king** [comment]
Hi John,

Thanks for the reply and now worries! We'll figure something out in the meantime :)
